name: Python application

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        python tests/test_main_page.py
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        # Private Key
        SSH_PRIVATE_KEY: 
        # Remote host
        REMOTE_HOST: 
        # Remote user
        REMOTE_USER: 
        # Remote port
        REMOTE_PORT: # optional, default is 22
        # Source directory
        SOURCE: # optional, default is 
        # Target directory
        TARGET: # optional, default is /home/REMOTE_USER/
        # Arguments to pass to rsync

    ARGS: # optional, default is -rltgoDzvO
